version: "3.9"

networks:
  app_network:

services:
  backendrds:
    build: ./backend_rds
    container_name: backend-rds
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    networks:
      - app_network

  backendredis:
    build: ./backend_redis
    container_name: backend-redis
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backendrds
      - backendredis
    networks:
      - app_network
